11. DVDStore [v1]/src/main/java/cat/jmir/dvdstore/model/Disc.java
package cat.jmir.dvdstore.model;

import java.text.DecimalFormat;

/**
 * JavaBean que conté l'informació d'un DVD 
 */
public class Disc {

	private int codi;
	private String titol;
	private String autor;
	private String[] etiquetes;
	private int unitats;
	private int preuEnCentims;
	
	public int getCodi() {
		return codi;
	}
	
	public void setCodi(int codi) {
		this.codi = codi;
	}
	
	public String getTitol() {
		return titol;
	}
	
	public void setTitol(String titol) {
		this.titol = titol;
	}

	public String getAutor() {
		return autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	public int getUnitats() {
		return unitats;
	}

	public void setUnitats(int unitats) {
		this.unitats = unitats;
	}
	
	public String[] getEtiquetes() {
		return etiquetes;
	}

	public void setEtiquetes(String[] etiquetes) {
		this.etiquetes = etiquetes;
	}
	
	public String getEtiquetesBeauty() {
		StringBuilder b = new StringBuilder();
		if(etiquetes != null && etiquetes.length > 0) {
			b.append(etiquetes[0]);
			for(int i=1;i<etiquetes.length;++i) {
				b.append(',').append(etiquetes[i]);
			}
		}
		return b.toString();
	}

	public int getPreuEnCentims() {
		return preuEnCentims;
	}
	
	public void setPreuEnCentims(int preuEnCentims) {
		this.preuEnCentims = preuEnCentims;
	}
	
	public String getPreuBeauty() {
		DecimalFormat df = new DecimalFormat("#.00");
		return df.format(getPreuEnCentims() / 100.0);
	}

	@Override
	public String toString() {
		return "Disc [codi=" + codi + ", titol=" + titol + ", autor=" + autor
				+ ", unitats=" + unitats + ", preuEnCentims=" + preuEnCentims
				+ "]";
	}
}
 

11. DVDStore [v1]/src/main/java/cat/jmir/dvdstore/DVDStoreServlet.java
package cat.jmir.dvdstore;

import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;

import cat.jmir.dvdstore.model.Disc;
import cat.jmir.dvdstore.service.dao.DAOException;
import cat.jmir.dvdstore.service.dao.DAOFactory;
import cat.jmir.dvdstore.service.dao.DiscDAO;
import cat.jmir.dvdstore.service.dao.sql.ConnectionProvider;
import cat.jmir.dvdstore.util.request.RequestReader;
import cat.jmir.dvdstore.util.request.RequestReaderException;

public class DVDStoreServlet extends HttpServlet {

	final static Logger logger = Logger.getLogger(ConnectionProvider.class);
	
	private static final long serialVersionUID = 1L;

	private DiscDAO discDAO = null;
	
	@Override
	public void init(ServletConfig config) throws ServletException {
		super.init(config);
		logger.info("Inicialització del servlet");
		discDAO = DAOFactory.createDiscDAO();
	}
	
	@Override
	public void destroy() {
		logger.info("Destrucció del servlet");
	}

	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String action = request.getParameter("action");
		if(action == null) action = "list"; //acció per defecte!
		String view = "/error.jsp";
		try {
			view = doGetAction(action, request);
		} catch (DAOException e) {
			logger.error("Excepció de DAO", e);
			throw new ServletException("Excepció de DAO", e);
		} catch (RequestReaderException e) {
			request.getSession().setAttribute("error", e.getMessage());
			view = "/error.jsp";
		}
		
		getServletConfig().getServletContext().getRequestDispatcher(view).forward(request,response);
	}
		
	private String doGetAction(String action, HttpServletRequest request) throws RequestReaderException, DAOException {	
		if(action.equalsIgnoreCase("edit")) {
			int codi = RequestReader.readDiscCodi(request);
			Disc disc = discDAO.loadDisc(codi);
			request.setAttribute("disc", disc);
			return "/update.jsp";
		} else { //if(action.equalsIgnoreCase("list")) {
			List<Disc> discs = discDAO.loadAllDisc();
			request.setAttribute("discs", discs);
			return "/index.jsp";
		}
	}

	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String action = request.getParameter("action");
		if(action == null) action = "none"; //acció per defecte!
		try {
			doPostAction(action, request);
		} catch (DAOException e) {
			logger.error("Excepció de DAO", e);
			throw new ServletException("Excepció de DAO", e);
		} catch (RequestReaderException e) {
			request.getSession().setAttribute("error", e.getMessage());
			getServletConfig().getServletContext().getRequestDispatcher("/error.jsp").forward(request,response);
			return;
		}
		
		//@see http://es.wikipedia.org/wiki/Post/Redirect/Get
		response.sendRedirect(".");
	}
	
	private void doPostAction(String action, HttpServletRequest request) throws RequestReaderException, DAOException {	
		if(action.equalsIgnoreCase("del")) {
			delDisc(request);
		} else if(action.equalsIgnoreCase("new")) {
			newDisc(request);
		} else if(action.equalsIgnoreCase("save_update")) {
			updateDisc(request);
		} else {
			logger.warn("Valor d'action desconegut: " + action);
		}
	}
	
	private void delDisc(HttpServletRequest request) throws RequestReaderException, DAOException {
		int[] codis = RequestReader.readDiscCodis(request);
		logger.info("action del: " + Arrays.toString(codis));
		if(codis.length > 0) {
			discDAO.removeDisc(codis);
		} else {
			logger.warn("s'ha provat d'esborrar 0 dvds");
		}
	}
	
	private void newDisc(HttpServletRequest request) throws RequestReaderException, DAOException {
		Disc d = RequestReader.readDisc(request);
		logger.info("action new:" + d);
		discDAO.storeDisc(d);
	}
	
	private void updateDisc(HttpServletRequest request) throws RequestReaderException, DAOException {
		Disc d = RequestReader.readDiscWithCodi(request);
		logger.info("action update:" + d);
		discDAO.updateDisc(d);
	}
}

11. DVDStore [v1]/src/main/webapp/error.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@page language="java" pageEncoding="utf-8"%>
<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Alta i baixa de DVDs</title>
<link rel="stylesheet" href="css/dvd.css" />
<link rel="stylesheet" href="css/foundation.css" />
<script src="js/vendor/modernizr.js"></script>
</head>
<body>
	
	<div id="myModal" class="reveal-modal full" data-reveal>
		<div class="row">
			<div class="large-2 columns">
				<a href="."><img src="img/error.gif" alt="error" /></a>
			</div>
			<div class="large-10 columns">
			  <h1>Error</h1>
			  <p class="lead">S'ha produït un error i tot el que se és això:</p> 
			  <p><span class="error">${error}</span></p>
			  <!-- Esborro la variable on es mostren els errors -->
			  <c:remove var="error"/>
			</div>
		</div>
		<div class="row">
			<div class="large-12 columns">
				<a class="button expand success" href=".">D'acord, no ho tornaré a fer</a>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="large-12 columns">
			<a class="button expand success" href=".">D'acord, no ho tornaré a fer</a>
		</div>
	</div>
	<!-- FOUNDATION JS -->
	<script src="js/vendor/jquery.js"></script>
	<script src="js/foundation.min.js"></script>
	<script>
		$(document).foundation();
	</script>
	<script>
		$(document).ready(
				function(){$('#myModal').foundation('reveal', 'open')}
		);
		$('#myModal').bind('closed', function() {
			 window.location.href = ".";
		});
	</script>
</body>
</html>

11. DVDStore [v1]/src/main/webapp/fatal.jsp
<%@page language="java" pageEncoding="utf-8" isErrorPage="true"%>
<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Alta i baixa de DVDs</title>
<link rel="stylesheet" href="css/dvd.css" />
<link rel="stylesheet" href="css/foundation.css" />
<script src="js/vendor/modernizr.js"></script>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="large-3 columns">
				<img src="img/fatal.gif" alt="error" />
			</div>
			<div class="large-9 columns">
				<h1>Error</h1>  
				<p><span class="error"><%= exception.getMessage() %></span></p>
				<p>L'error ha estat noficat i en breu hi possarem sol·lució</p>
			</div>
		</div>
	</div>
				
	
	<!-- FOUNDATION JS -->
	<script src="js/vendor/jquery.js"></script>
	<script src="js/foundation.min.js"></script>
	<script>
		$(document).foundation();
	</script>
</body>
</html>

11. DVDStore [v1]/src/main/webapp/index.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@page language="java" pageEncoding="utf-8"%>
<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Alta i baixa de DVDs</title>
<link rel="stylesheet" href="css/dvd.css" />
<link rel="stylesheet" href="css/foundation.css" />
<script src="js/vendor/modernizr.js"></script>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="large-2 columns">
				<img src="img/dvd-logo.jpg" width="100" alt="DVD"/>
			</div>
			<div class="large-10 columns">
				<h1>Alta i baixa de DVDs</h1>
			</div>
			<hr />
			<div class="large-12 columns">
			<form method="post" action=".">
				<c:if test="${!discs.isEmpty()}">
					<div class="row">
						<div class="large-1 columns">
							<button class="button tiny alert expand" name="action" value="del"
								type="submit">Esborrar</button>
						</div>
						<div class="large-1 columns">
							<h4>Codi</h4>
						</div>
						<div class="large-2 columns">
							<h4>Tí­tol</h4>
						</div>
						<div class="large-2 columns">
							<h4>Autor</h4>
						</div>
						<div class="large-2 columns">
							<h4>Preu</h4>
						</div>
						<div class="large-2 columns">
							<h4>Etiquetes</h4>
						</div>
						<div class="large-2 columns">
							<h4>Unitats</h4>
						</div>
					</div>
					<c:forEach var="disc" items="${discs}">
						<div class="row item">
							<div class="large-1 columns">
								<div class="switch small">
								  <input id="checkbox${disc.codi}" type="checkbox" name="codi"
										value="${disc.codi}">
								  <label for="checkbox${disc.codi}"></label>
								</div> 
							</div>
							<div class="large-1 columns">${disc.codi}</div>
							<div class="large-2 columns">${disc.titol}</div>
							<div class="large-2 columns">${disc.autor}</div>
							<div class="large-2 columns">${disc.preuBeauty} &euro;</div>
							<div class="large-2 columns">
								<select>
									<c:forEach var="etiqueta" items="${disc.etiquetes}">
										<option>${etiqueta}</option>				
									</c:forEach>
								</select>
							</div>
							<div class="large-1 columns">${disc.unitats}</div>
							<div class="large-1 columns">
								<a href="?action=edit&codi=${disc.codi}" class="button tiny expand">Edit</a>
							</div>
						</div>
					</c:forEach>
				</c:if>
			</form>
			<div class="row">
				<hr />
				<form id="insertForm" method="post" action=".">
					<div class="large-2 columns">
						<button class="button tiny expand success" name="action"
							value="new" type="submit">Nou disc</button>
					</div>
					<div class="large-2 columns">
						<input type="text" name="titol" placeholder="Títol del nou disc" />
					</div>
					<div class="large-2 columns">
						<input type="text" name="autor" placeholder="Autor del nou disc" />
					</div>
					<div class="large-2 columns">
						<div class="row collapse postfix-radius">
							<div class="small-8 columns">
								<input type="text" name="preu" placeholder="XX.XX"/>
							</div>
							<div class="small-4 columns">
								<span class="postfix">&euro;</span>
							</div>
						</div>
					</div>
					<div class="large-2 columns">
						<input type="text" name="etiquetes" placeholder="comedia,usa" />
					</div>
					<div class="large-2 columns">
						<input type="text" name="unitats" placeholder="Unitats" />
					</div>
				</form>		
				</div>
			</div>
		</div>
	</div>

	<!-- FOUNDATION JS -->
	<script src="js/vendor/jquery.js"></script>
	<script src="js/foundation.min.js"></script>
	<script>
		$(document).foundation();
	</script>
	<!-- JQUERY VALIDATION -->
	<script src="js/jquery.validate.min.js"></script>
	<script>
	$(document).ready(function() {
		$('.error').delay(5000).fadeOut('slow');
	    
		$.validator.addMethod('preuCorrecte', function (value, element, param) {
		    return /^[1-9]\d+(\.\d\d?)?$/.test(value);
		}, 'Preu incorrecte');
		
		$("#insertForm").validate({
			rules: {
				titol: "required",
				autor: "required",
				preu : { 
					preuCorrecte : true 
				},
				unitats: {
					required: true,
					min: 0,
					number: true
				}
			},
			messages: {
				titol: "Introdueix un títol",
				autor: "Introdueix un autor",
				unitats: "Nombre d'unitats incorrecte"
			}, 
			errorPlacement: function(error, element) {
				 error.insertAfter( element).position({
	                  my:'right top',
	                  at:'right top',
	                  of:element          
	              });
	              error.fadeOut(5000);
	        }
		});
		
		
	});
	</script>
</body>
</html>

11. DVDStore [v1]/src/main/webapp/update.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@page language="java" pageEncoding="utf-8"%>
<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Alta i baixa de DVDs</title>
<link rel="stylesheet" href="css/dvd.css" />
<link rel="stylesheet" href="css/foundation.css" />
<script src="js/vendor/modernizr.js"></script>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="large-2 columns">
				<img src="img/dvd-logo.jpg" width="100" alt="DVD"/>
			</div>
			<div class="large-10 columns">
				<h1>Editar DVD</h1>
			</div>
			<hr />
			<div class="large-12 columns">
			<form id="updateForm" method="post" action=".">
				<div class="row">
					<div class="large-2 columns">
						<h4>Codi</h4>
					</div>
					<div class="large-2 columns">
						<h4>Tí­tol</h4>
					</div>
					<div class="large-2 columns">
						<h4>Autor</h4>
					</div>
					<div class="large-2 columns">
						<h4>Preu</h4>
					</div>
					<div class="large-2 columns">
						<h4>Etiquetes</h4>
					</div>					
					<div class="large-2 columns">
						<h4>Unitats</h4>
					</div>
				</div>
				<div class="row">
					<div class="large-2 columns">
						<input type="text" value="${disc.codi}" disabled />
						<input type="hidden" name="codi" value="${disc.codi}"/>
					</div>
					<div class="large-2 columns">
						<input type="text" name="titol" value="${disc.titol}" />
					</div>
					<div class="large-2 columns">
						<input type="text" name="autor"  value="${disc.autor}" />
					</div>
					<div class="large-2 columns">
						<div class="row collapse postfix-radius">
							<div class="small-8 columns">
								<input type="text" name="preu" value="${disc.preuBeauty}"/>
							</div>
							<div class="small-4 columns">
								<span class="postfix">&euro;</span>
							</div>
						</div>
					</div>
					<div class="large-2 columns">
						<input type="text" name="etiquetes"  value="${disc.etiquetesBeauty}" />
					</div>
					<div class="large-2 columns">
						<input type="text" name="unitats"  value="${disc.unitats}" />
					</div>
				</div>
				<div class="row">
					<div class="large-4 columns">
						<button class="button tiny expand success" name="action" value="save_update"
							type="submit">Guardar</button>
					</div>
					<div class="large-4 columns">
						<button class="button tiny alert expand" name="action" value="del"
							type="submit">Esborrar</button>
					</div>
					<div class="large-4 columns">
						<a href="." class="button tiny warning expand"
							type="submit">Cancelar</a>
					</div>
				</div>
			</form>
			</div>
		</div>
	</div>
	<!-- Esborro la variable on es mostren els errors -->
	<c:remove var="error"/>

	<!-- FOUNDATION JS -->
	<script src="js/vendor/jquery.js"></script>
	<script src="js/foundation.min.js"></script>
	<script>
		$(document).foundation();
	</script>
	<!-- JQUERY VALIDATION -->
	<script src="js/jquery.validate.min.js"></script>
	<script>
	$(document).ready(function() {
		$('.error').delay(5000).fadeOut('slow');
	    
		$.validator.addMethod('preuCorrecte', function (value, element, param) {
		    return /^[1-9]\d+(\.\d\d?)?$/.test(value);
		}, 'Preu incorrecte');
		
		$("#updateForm").validate({
			rules: {
				titol: "required",
				autor: "required",
				preu : { 
					preuCorrecte : true 
				},
				unitats: {
					required: true,
					min: 0,
					number: true
				}
			},
			messages: {
				titol: "Introdueix un títol",
				autor: "Introdueix un autor",
				unitats: "Nombre d'unitats incorrecte"
			}, 
			errorPlacement: function(error, element) {
				 error.insertAfter( element).position({
	                  my:'right top',
	                  at:'right top',
	                  of:element          
	              });
	              error.fadeOut(5000);
	        }
		});
	});
	</script>
</body>
</html>